/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.migestion.swing.custom;

import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author bernardo
 */
public class CriteriaFechaRangoPanel extends javax.swing.JPanel {

    /**
     * Creates new form CriteriaFechaRangoPanel
     */
    public CriteriaFechaRangoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup = new javax.swing.ButtonGroup();
        rdbtnRango = new javax.swing.JRadioButton();
        pickerDesde = new com.toedter.calendar.JDateChooser();
        pickerHasta = new com.toedter.calendar.JDateChooser();
        rdBtnSemanaActual = new javax.swing.JRadioButton();
        rdBtnMesActual = new javax.swing.JRadioButton();
        rdBtnAnioActual = new javax.swing.JRadioButton();

        setLayout(new java.awt.GridBagLayout());

        buttonGroup.add(rdbtnRango);
        rdbtnRango.setText("Rango");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(rdbtnRango, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(pickerDesde, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(pickerHasta, gridBagConstraints);

        buttonGroup.add(rdBtnSemanaActual);
        rdBtnSemanaActual.setSelected(true);
        rdBtnSemanaActual.setText("Esta semana");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(rdBtnSemanaActual, gridBagConstraints);

        buttonGroup.add(rdBtnMesActual);
        rdBtnMesActual.setText("Este mes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(rdBtnMesActual, gridBagConstraints);

        buttonGroup.add(rdBtnAnioActual);
        rdBtnAnioActual.setText("Este Anio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(rdBtnAnioActual, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private com.toedter.calendar.JDateChooser pickerDesde;
    private com.toedter.calendar.JDateChooser pickerHasta;
    private javax.swing.JRadioButton rdBtnAnioActual;
    private javax.swing.JRadioButton rdBtnMesActual;
    private javax.swing.JRadioButton rdBtnSemanaActual;
    private javax.swing.JRadioButton rdbtnRango;
    // End of variables declaration//GEN-END:variables


    public void setMesActual(){
		rdBtnMesActual.setSelected(true);
		pickerDesde.setDate( null );
		pickerHasta.setDate( null );
	}
	
	public void setSemanaActual(){
		rdBtnSemanaActual.setSelected(true);
		pickerDesde.setDate( null );
		pickerHasta.setDate( null );
	}
	
	public void setAnioActual(){
		rdBtnAnioActual.setSelected(true);
		pickerDesde.setDate( null );
		pickerHasta.setDate( null );
	}
	
	public void setFechaDesde(Date fecha){
		pickerDesde.setDate( fecha );
	}
	
	public void setFechaHasta(Date fecha){
		pickerHasta.setDate( fecha );
	}
	
	public Date[] getFechas(){
		
		Date desde = null;
		Date hasta = null;
		
				
		Calendar calendar1 = Calendar.getInstance();
		Calendar calendar2 = Calendar.getInstance();
			
		if(rdBtnSemanaActual.isSelected()){
			calendar1.set( Calendar.DAY_OF_WEEK, 1);
			calendar2.set( Calendar.DAY_OF_WEEK, calendar2.getActualMaximum(Calendar.DAY_OF_WEEK));
		}
			
		if(rdBtnMesActual.isSelected()){
			calendar1.set( Calendar.DAY_OF_MONTH, 1);
			calendar2.set( Calendar.DAY_OF_MONTH, calendar2.getActualMaximum(Calendar.DAY_OF_MONTH));
		}
			
		if(rdBtnAnioActual.isSelected()){
			calendar1.set( Calendar.DAY_OF_YEAR, 1);
			calendar2.set( Calendar.DAY_OF_YEAR, calendar2.getActualMaximum(Calendar.DAY_OF_YEAR));
		}
		desde = calendar1.getTime();
		hasta = calendar2.getTime();
			
		if(rdbtnRango.isSelected()){
			desde = pickerDesde.getDate();
			hasta = pickerHasta.getDate();
		}
		
		Date[] fechas = {desde, hasta}; 
		return fechas;
	}
}
