/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.migestion.swing.custom;

import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author bernardo
 */
public class CriteriaFechaRangoPanel extends javax.swing.JPanel {

    /**
     * Creates new form CriteriaFechaRangoPanel
     */
    public CriteriaFechaRangoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        rdbtnRango = new javax.swing.JRadioButton();
        pickerDesde = new com.toedter.calendar.JDateChooser();
        pickerHasta = new com.toedter.calendar.JDateChooser();
        rdBtnSemanaActual = new javax.swing.JRadioButton();
        rdBtnMesActual = new javax.swing.JRadioButton();
        rdBtnAnioActual = new javax.swing.JRadioButton();
        rdBtnHoy = new javax.swing.JRadioButton();

        buttonGroup.add(rdbtnRango);
        rdbtnRango.setText("Rango");

        buttonGroup.add(rdBtnSemanaActual);
        rdBtnSemanaActual.setText("Esta semana");

        buttonGroup.add(rdBtnMesActual);
        rdBtnMesActual.setText("Este mes");

        buttonGroup.add(rdBtnAnioActual);
        rdBtnAnioActual.setText("Este Año");

        buttonGroup.add(rdBtnHoy);
        rdBtnHoy.setSelected(true);
        rdBtnHoy.setText("Hoy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdBtnHoy)
                    .addComponent(rdbtnRango))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdBtnSemanaActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdBtnMesActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdBtnAnioActual))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pickerDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pickerHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtnHoy)
                    .addComponent(rdBtnSemanaActual)
                    .addComponent(rdBtnMesActual)
                    .addComponent(rdBtnAnioActual))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pickerHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pickerDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnRango))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private com.toedter.calendar.JDateChooser pickerDesde;
    private com.toedter.calendar.JDateChooser pickerHasta;
    private javax.swing.JRadioButton rdBtnAnioActual;
    private javax.swing.JRadioButton rdBtnHoy;
    private javax.swing.JRadioButton rdBtnMesActual;
    private javax.swing.JRadioButton rdBtnSemanaActual;
    private javax.swing.JRadioButton rdbtnRango;
    // End of variables declaration//GEN-END:variables


    public void setMesActual(){
		rdBtnMesActual.setSelected(true);
		pickerDesde.setDate( null );
		pickerHasta.setDate( null );
	}
	
	public void setSemanaActual(){
		rdBtnSemanaActual.setSelected(true);
		pickerDesde.setDate( null );
		pickerHasta.setDate( null );
	}
	
	public void setAnioActual(){
		rdBtnAnioActual.setSelected(true);
		pickerDesde.setDate( null );
		pickerHasta.setDate( null );
	}
	
	public void setFechaDesde(Date fecha){
		pickerDesde.setDate( fecha );
	}
	
	public void setFechaHasta(Date fecha){
		pickerHasta.setDate( fecha );
	}
	
	public Date[] getFechas(){
		
		Date desde = null;
		Date hasta = null;
		
				
		Calendar calendar1 = Calendar.getInstance();
		Calendar calendar2 = Calendar.getInstance();

		if(rdBtnHoy.isSelected()){
                    calendar1.set(Calendar.MINUTE, 0);
                    calendar1.set(Calendar.HOUR, 0);
                    calendar1.set(Calendar.SECOND, 0);
                    calendar1.set(Calendar.AM_PM, Calendar.AM);

                    calendar2.set(Calendar.MINUTE, 59);
                    calendar2.set(Calendar.HOUR, 11);
                    calendar2.set(Calendar.SECOND, 59);
                    calendar2.set(Calendar.AM_PM, Calendar.PM);                   
                    
		}
                
		if(rdBtnSemanaActual.isSelected()){
			calendar1.set( Calendar.DAY_OF_WEEK, 1);
			calendar2.set( Calendar.DAY_OF_WEEK, calendar2.getActualMaximum(Calendar.DAY_OF_WEEK));
		}
			
		if(rdBtnMesActual.isSelected()){
			calendar1.set( Calendar.DAY_OF_MONTH, 1);
			calendar2.set( Calendar.DAY_OF_MONTH, calendar2.getActualMaximum(Calendar.DAY_OF_MONTH));
		}
			
		if(rdBtnAnioActual.isSelected()){
			calendar1.set( Calendar.DAY_OF_YEAR, 1);
			calendar2.set( Calendar.DAY_OF_YEAR, calendar2.getActualMaximum(Calendar.DAY_OF_YEAR));
		}
		desde = calendar1.getTime();
		hasta = calendar2.getTime();
			
		if(rdbtnRango.isSelected()){
			desde = pickerDesde.getDate();
			hasta = pickerHasta.getDate();
		}
		
		Date[] fechas = {desde, hasta}; 
		return fechas;
	}
}
